#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Killing ESD"
    killall /usr/bin/esd > /dev/null 2> /dev/null
    stat_done
    ;;
  stop)
    stat_busy "Killing ESD"
    killall /usr/bin/esd > /dev/null 2> /dev/null
    stat_done
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
