#!/usr/bin/env ruby

# Michael Dominic K. <mdk@mdk.am>
# Prints a colorfull mail status

def parse_dir(dir)
  count = 0
  path = File.join(dir, "new")
  Dir.open(path).each { |entry|
    full_name = File.join(path, entry)
    next if File.ftype(full_name) != "file"
    next if entry == "." or entry == ".."

    count += 1
  }
  return count
end

puts "Unread mail:"
mail_dir = File.join(ENV['HOME'], 'Mail')

Dir.open(mail_dir).each { |entry|
  
  full_name = File.join(mail_dir, entry)
  
  next if entry =~ /^\[/ 
  next if File.ftype(full_name) != "directory"
  next if entry == "." or entry == ".."

  count = parse_dir(full_name)
  puts "  * #{entry} [\033[1;33m#{count}\033[0m]" if count > 0
}

