#!/usr/bin/env ruby

@@module_name = "Hildon"
@@parent_type = "GTK_TYPE_DRAWINGAREA"
@@parent = "GtkDrawingArea"
@@namespace = "Hildon"
@@object_name = "ScrollBar"

def underscorize(str)
  out = ""
  first = true
  str.each_byte { |byte| 
    if byte.chr.swapcase == byte.chr.downcase and not first
      out = out + "_" + byte.chr
    else
      out = out + byte.chr
    end
    first = false
  }

  return out
end

def minusize(str)
  out = ""
  first = true
  str.each_byte { |byte| 
    if byte.chr.swapcase == byte.chr.downcase and not first
      out = out + "-" + byte.chr
    else
      out = out + byte.chr
    end
    first = false
  }

  return out
end

def substitute(stream)

  stream.gsub!("XG_TYPE_XOBJECT_PARENT", @@parent_type)
  stream.gsub!("XgXobjectParent", @@parent)
  stream.gsub!("XG_XOBJECT", underscorize(@@namespace).upcase + "_" + underscorize(@@object_name).upcase)
  stream.gsub!("Xg_Xobject", underscorize(@@namespace) + "_" + underscorize(@@object_name));
  stream.gsub!("xg-xobject", minusize(@@namespace).downcase + "-" + minusize(@@object_name).downcase);
  stream.gsub!("XgXobject", @@namespace + @@object_name);
  stream.gsub!("xg_xobject", underscorize(@@namespace).downcase + "_" + underscorize(@@object_name).downcase)
  stream.gsub!("XG_TYPE", underscorize(@@namespace).upcase + "_TYPE")
  stream.gsub!("XG", underscorize(@@namespace).upcase)
  stream.gsub!("XOBJECT", underscorize(@@object_name).upcase)
  stream.gsub!("XName", @@module_name)

  return stream
end

def dofile(input, output)
  f = File.new(input, "rb")
  data = f.read
  data = substitute(data)
  len = 0;
  out = File.new(output, "w");
  data.each_line { |line|

    next if line == ""

    if line.index("___align___") == 0 then
      str = ""
      for num in (1..len)
        str = str + " "
      end
      line.gsub!("___align___", str)
    else
      first = line.split(' ') [0]
      len = first.length if first != nil
    end

    out.puts "#{line}"
  }

end

# Read the input
puts  "GObject magic generate!"

print "Enter the module name [ie. Hildon]               : "
@@module_name = gets.gsub!("\n", "")

print "Enter the parent type [ie. GTK_TYPE_DRAWINGAREA] : "
@@parent_type = gets.gsub!("\n", "")

print "Enter the parent [ie. GtkDrawingArea]            : "
@@parent = gets.gsub!("\n", "")

print "Enter the namespace [ie. Hildon]                 : "
@@namespace = gets.gsub!("\n", "")

print "Enter the object name [ie. ScrollBar]            : "
@@object_name = gets.gsub!("\n", "")

dofile("/usr/share/gobject-generate/xg-xobject.c", "#{minusize(@@namespace).downcase}-#{minusize(@@object_name).downcase}.c")
dofile("/usr/share/gobject-generate/xg-xobject.h", "#{minusize(@@namespace).downcase}-#{minusize(@@object_name).downcase}.h")
dofile("/usr/share/gobject-generate/xg-xobject-private.h", "#{minusize(@@namespace).downcase}-#{minusize(@@object_name).downcase}-private.h")

