#!/usr/bin/env ruby

# Michael Dominic K. <mdk@mdk.am>

# Executes the git status command and prints the entries
# into ChangeLog-like format for easy editing.
#
# Use in vim with !r git2changelog.rb to paste a nice summary
# into ChangeLog.

# Customize here
name="Michael Dominic K."
email="mdk@mdk.am"

ary = []
`git status`.each do |line|
  match = line.scan(/.*[modified|deleted]:\s*(.+)/)
  ary << match[0][0] if not match.empty?
end

# Sort the entries
ary = ary.sort

# Print the header
print Time.now.strftime("%Y-%m-%d") + "  " + name + "  " + "<" + email + ">" " \n\n"

# Print all the entries
ary.each do |line|
  print "\t* " + line + ":\n"
end

print "\n"
